// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: notificacion.proto

package notificacionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Notificacion_ProveedorNotificacion_FullMethodName = "/notificacion.Notificacion/ProveedorNotificacion"
	Notificacion_ClienteNotificacion_FullMethodName   = "/notificacion.Notificacion/ClienteNotificacion"
)

// NotificacionClient is the client API for Notificacion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificacionClient interface {
	ProveedorNotificacion(ctx context.Context, in *ProveedorNotificacionRequest, opts ...grpc.CallOption) (*ProveedorNotificacionResponse, error)
	ClienteNotificacion(ctx context.Context, in *ClienteNotificacionRequest, opts ...grpc.CallOption) (*ClienteNotificacionResponse, error)
}

type notificacionClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificacionClient(cc grpc.ClientConnInterface) NotificacionClient {
	return &notificacionClient{cc}
}

func (c *notificacionClient) ProveedorNotificacion(ctx context.Context, in *ProveedorNotificacionRequest, opts ...grpc.CallOption) (*ProveedorNotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveedorNotificacionResponse)
	err := c.cc.Invoke(ctx, Notificacion_ProveedorNotificacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificacionClient) ClienteNotificacion(ctx context.Context, in *ClienteNotificacionRequest, opts ...grpc.CallOption) (*ClienteNotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClienteNotificacionResponse)
	err := c.cc.Invoke(ctx, Notificacion_ClienteNotificacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificacionServer is the server API for Notificacion service.
// All implementations must embed UnimplementedNotificacionServer
// for forward compatibility.
type NotificacionServer interface {
	ProveedorNotificacion(context.Context, *ProveedorNotificacionRequest) (*ProveedorNotificacionResponse, error)
	ClienteNotificacion(context.Context, *ClienteNotificacionRequest) (*ClienteNotificacionResponse, error)
	mustEmbedUnimplementedNotificacionServer()
}

// UnimplementedNotificacionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificacionServer struct{}

func (UnimplementedNotificacionServer) ProveedorNotificacion(context.Context, *ProveedorNotificacionRequest) (*ProveedorNotificacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProveedorNotificacion not implemented")
}
func (UnimplementedNotificacionServer) ClienteNotificacion(context.Context, *ClienteNotificacionRequest) (*ClienteNotificacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClienteNotificacion not implemented")
}
func (UnimplementedNotificacionServer) mustEmbedUnimplementedNotificacionServer() {}
func (UnimplementedNotificacionServer) testEmbeddedByValue()                      {}

// UnsafeNotificacionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificacionServer will
// result in compilation errors.
type UnsafeNotificacionServer interface {
	mustEmbedUnimplementedNotificacionServer()
}

func RegisterNotificacionServer(s grpc.ServiceRegistrar, srv NotificacionServer) {
	// If the following call panics, it indicates UnimplementedNotificacionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notificacion_ServiceDesc, srv)
}

func _Notificacion_ProveedorNotificacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveedorNotificacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificacionServer).ProveedorNotificacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notificacion_ProveedorNotificacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificacionServer).ProveedorNotificacion(ctx, req.(*ProveedorNotificacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notificacion_ClienteNotificacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClienteNotificacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificacionServer).ClienteNotificacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notificacion_ClienteNotificacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificacionServer).ClienteNotificacion(ctx, req.(*ClienteNotificacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notificacion_ServiceDesc is the grpc.ServiceDesc for Notificacion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notificacion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notificacion.Notificacion",
	HandlerType: (*NotificacionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProveedorNotificacion",
			Handler:    _Notificacion_ProveedorNotificacion_Handler,
		},
		{
			MethodName: "ClienteNotificacion",
			Handler:    _Notificacion_ClienteNotificacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notificacion.proto",
}
