apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  labels:
    app: pricing
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
        tier: backend
    spec:
      containers:
        - name: pricing
          image: 11erick21/pricing:2.0
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
          ports:
            - name: grpc
              containerPort: 50052
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3