syntax = "proto3";

package auth;
option go_package = "/proto;auth";

service AuthService {
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc GetUserById (GetUserByIdRequest) returns (GetUserByIdResponse);
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  bool valid = 1;
  int32 user_id = 2;
  string email = 3;
  string role = 4;
  string error = 5;
}

message GetUserByIdRequest {
  int32 user_id = 1;
}

message GetUserByIdResponse {
  int32 id = 1;
  string email = 2;
  string first_name = 3;
  string last_name = 4;
  string nit = 5;
  string phone = 6;
  string role = 7;
}
