# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notificacion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notificacion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notificacion.proto\x12\x0cnotificacion\"=\n\x14ProductoNotificacion\x12\x13\n\x0bid_producto\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\"\xa0\x01\n\x1cProveedorNotificacionRequest\x12\x14\n\x0cid_proveedor\x18\x01 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\x12\x35\n\tproductos\x18\x05 \x03(\x0b\x32\".notificacion.ProductoNotificacion\"}\n\x1dProveedorNotificacionResponse\x12\x14\n\x0cid_proveedor\x18\x01 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\x12\x11\n\tresultado\x18\x05 \x01(\t\"\xbd\x01\n\x1a\x43lienteNotificacionRequest\x12\x12\n\nid_usuario\x18\x01 \x01(\x05\x12\x10\n\x08id_carro\x18\x02 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x0c\n\x04tipo\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x10\n\x08id_orden\x18\x06 \x01(\t\x12\x35\n\tproductos\x18\x07 \x03(\x0b\x32\".notificacion.ProductoNotificacion\"\x88\x01\n\x1b\x43lienteNotificacionResponse\x12\x12\n\nid_usuario\x18\x01 \x01(\x05\x12\x10\n\x08id_carro\x18\x02 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x0c\n\x04tipo\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x11\n\tresultado\x18\x06 \x01(\t2\xf0\x01\n\x0cNotificacion\x12r\n\x15ProveedorNotificacion\x12*.notificacion.ProveedorNotificacionRequest\x1a+.notificacion.ProveedorNotificacionResponse\"\x00\x12l\n\x13\x43lienteNotificacion\x12(.notificacion.ClienteNotificacionRequest\x1a).notificacion.ClienteNotificacionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificacion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTONOTIFICACION']._serialized_start=36
  _globals['_PRODUCTONOTIFICACION']._serialized_end=97
  _globals['_PROVEEDORNOTIFICACIONREQUEST']._serialized_start=100
  _globals['_PROVEEDORNOTIFICACIONREQUEST']._serialized_end=260
  _globals['_PROVEEDORNOTIFICACIONRESPONSE']._serialized_start=262
  _globals['_PROVEEDORNOTIFICACIONRESPONSE']._serialized_end=387
  _globals['_CLIENTENOTIFICACIONREQUEST']._serialized_start=390
  _globals['_CLIENTENOTIFICACIONREQUEST']._serialized_end=579
  _globals['_CLIENTENOTIFICACIONRESPONSE']._serialized_start=582
  _globals['_CLIENTENOTIFICACIONRESPONSE']._serialized_end=718
  _globals['_NOTIFICACION']._serialized_start=721
  _globals['_NOTIFICACION']._serialized_end=961
# @@protoc_insertion_point(module_scope)
