apiVersion: v1
kind: Service
metadata:
  name: notificaciones-service
  labels:
    app: notificaciones
spec:
  selector:
    app: notificaciones
  ports:
    - name: http
      port: 8087
      targetPort: 8087
    - name: grpc
      port: 50056
      targetPort: 50056
  type: NodePort
