apiVersion: v1
kind: Secret
metadata:
  name: notificaciones-secret
type: Opaque
stringData:
  DB_HOST: "mssql"
  DB_PORT: "1433"
  DB_USER: "sa"
  DB_PASSWORD: "YourStrong@Passw0rd123!"
  DB_NAME: "EconoMarketNotificacionesDB"
  GRPC_PORT: "50056"
  HTTP_PORT: "8087"
  AUTH_SERVICE_HOST: "users-auth"
  AUTH_SERVICE_PORT: "50051"
  CATALOG_SERVICE_HOST: "catalog-service"
  CATALOG_SERVICE_PORT: "50058"
  ORDER_SERVICE_HOST: "orders-service"
  ORDER_SERVICE_PORT: "50052"