# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orders_pb2 as orders__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrdersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/orders.OrdersService/CreateOrder',
                request_serializer=orders__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.CreateOrderFromCart = channel.unary_unary(
                '/orders.OrdersService/CreateOrderFromCart',
                request_serializer=orders__pb2.CreateOrderFromCartRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/orders.OrdersService/GetOrder',
                request_serializer=orders__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOrdersByUser = channel.unary_unary(
                '/orders.OrdersService/GetOrdersByUser',
                request_serializer=orders__pb2.GetOrdersByUserRequest.SerializeToString,
                response_deserializer=orders__pb2.OrdersListResponse.FromString,
                _registered_method=True)
        self.GetAllOrders = channel.unary_unary(
                '/orders.OrdersService/GetAllOrders',
                request_serializer=orders__pb2.Empty.SerializeToString,
                response_deserializer=orders__pb2.OrdersListResponse.FromString,
                _registered_method=True)
        self.UpdateOrderStatus = channel.unary_unary(
                '/orders.OrdersService/UpdateOrderStatus',
                request_serializer=orders__pb2.UpdateOrderStatusRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderResponse.FromString,
                _registered_method=True)


class OrdersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrderFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrdersByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=orders__pb2.CreateOrderRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
            'CreateOrderFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrderFromCart,
                    request_deserializer=orders__pb2.CreateOrderFromCartRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=orders__pb2.GetOrderRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrdersByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrdersByUser,
                    request_deserializer=orders__pb2.GetOrdersByUserRequest.FromString,
                    response_serializer=orders__pb2.OrdersListResponse.SerializeToString,
            ),
            'GetAllOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOrders,
                    request_deserializer=orders__pb2.Empty.FromString,
                    response_serializer=orders__pb2.OrdersListResponse.SerializeToString,
            ),
            'UpdateOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrderStatus,
                    request_deserializer=orders__pb2.UpdateOrderStatusRequest.FromString,
                    response_serializer=orders__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.OrdersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orders.OrdersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrdersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrdersService/CreateOrder',
            orders__pb2.CreateOrderRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrderFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrdersService/CreateOrderFromCart',
            orders__pb2.CreateOrderFromCartRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrdersService/GetOrder',
            orders__pb2.GetOrderRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrdersByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrdersService/GetOrdersByUser',
            orders__pb2.GetOrdersByUserRequest.SerializeToString,
            orders__pb2.OrdersListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrdersService/GetAllOrders',
            orders__pb2.Empty.SerializeToString,
            orders__pb2.OrdersListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.OrdersService/UpdateOrderStatus',
            orders__pb2.UpdateOrderStatusRequest.SerializeToString,
            orders__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
