# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"\x07\n\x05\x45mpty\"\x9b\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\r\n\x05stock\x18\x06 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x10\n\x08imageUrl\x18\x08 \x01(\t\x12\x12\n\nproviderId\x18\t \x01(\x05\":\n\x14ListProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.catalog.Product\"\x1e\n\x10ProductIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x9c\x01\n\x14\x43reateProductRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x10\n\x08imageUrl\x18\x07 \x01(\t\x12\x12\n\nproviderId\x18\x08 \x01(\x05\"\xa8\x01\n\x14UpdateProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\r\n\x05stock\x18\x06 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x10\n\x08imageUrl\x18\x08 \x01(\t\x12\x12\n\nproviderId\x18\t \x01(\x05\"\"\n\x0fGenericResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe4\x02\n\x0e\x43\x61talogService\x12=\n\x0cListProducts\x12\x0e.catalog.Empty\x1a\x1d.catalog.ListProductsResponse\x12\x39\n\nGetProduct\x12\x19.catalog.ProductIdRequest\x1a\x10.catalog.Product\x12H\n\rCreateProduct\x12\x1d.catalog.CreateProductRequest\x1a\x18.catalog.GenericResponse\x12H\n\rUpdateProduct\x12\x1d.catalog.UpdateProductRequest\x1a\x18.catalog.GenericResponse\x12\x44\n\rDeleteProduct\x12\x19.catalog.ProductIdRequest\x1a\x18.catalog.GenericResponseB\x1cZ\x1a\x63\x61talog/internal/grpc;grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032catalog/internal/grpc;grpc'
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PRODUCT']._serialized_start=36
  _globals['_PRODUCT']._serialized_end=191
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=193
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=251
  _globals['_PRODUCTIDREQUEST']._serialized_start=253
  _globals['_PRODUCTIDREQUEST']._serialized_end=283
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=286
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=442
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=445
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=613
  _globals['_GENERICRESPONSE']._serialized_start=615
  _globals['_GENERICRESPONSE']._serialized_end=649
  _globals['_CATALOGSERVICE']._serialized_start=652
  _globals['_CATALOGSERVICE']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
