services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  users-auth:
    build: .              # ← ahora el contexto es la carpeta users-auth
    container_name: users-auth-service
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      DB_HOST: mssql
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: YourStrong@Passw0rd123!
      DB_NAME: economarket
      JWT_SECRET: super-secret-jwt-key
      HTTP_PORT: 8080
      GRPC_PORT: 50051
    depends_on:
      - mssql

volumes:
  mssql_data:
