apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  # JWT Secret
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXk=
  # Usuario BD: sa
  db-username: c2E=
  # Contraseña BD: YourStrong@Passw0rd123!
  db-password: WW91clN0cm9uZ0BQYXNzdzByZDEyMyE=
