// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: notificacion.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductoNotificacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdProducto    int32                  `protobuf:"varint,1,opt,name=id_producto,json=idProducto,proto3" json:"id_producto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductoNotificacion) Reset() {
	*x = ProductoNotificacion{}
	mi := &file_notificacion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductoNotificacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductoNotificacion) ProtoMessage() {}

func (x *ProductoNotificacion) ProtoReflect() protoreflect.Message {
	mi := &file_notificacion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductoNotificacion.ProtoReflect.Descriptor instead.
func (*ProductoNotificacion) Descriptor() ([]byte, []int) {
	return file_notificacion_proto_rawDescGZIP(), []int{0}
}

func (x *ProductoNotificacion) GetIdProducto() int32 {
	if x != nil {
		return x.IdProducto
	}
	return 0
}

type ProveedorNotificacionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	IdProveedor   int32                   `protobuf:"varint,1,opt,name=id_proveedor,json=idProveedor,proto3" json:"id_proveedor,omitempty"`
	Estado        string                  `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Mensaje       string                  `protobuf:"bytes,4,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Productos     []*ProductoNotificacion `protobuf:"bytes,5,rep,name=productos,proto3" json:"productos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveedorNotificacionRequest) Reset() {
	*x = ProveedorNotificacionRequest{}
	mi := &file_notificacion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveedorNotificacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveedorNotificacionRequest) ProtoMessage() {}

func (x *ProveedorNotificacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificacion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveedorNotificacionRequest.ProtoReflect.Descriptor instead.
func (*ProveedorNotificacionRequest) Descriptor() ([]byte, []int) {
	return file_notificacion_proto_rawDescGZIP(), []int{1}
}

func (x *ProveedorNotificacionRequest) GetIdProveedor() int32 {
	if x != nil {
		return x.IdProveedor
	}
	return 0
}

func (x *ProveedorNotificacionRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ProveedorNotificacionRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProveedorNotificacionRequest) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ProveedorNotificacionRequest) GetProductos() []*ProductoNotificacion {
	if x != nil {
		return x.Productos
	}
	return nil
}

type ProveedorNotificacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdProveedor   int32                  `protobuf:"varint,1,opt,name=id_proveedor,json=idProveedor,proto3" json:"id_proveedor,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Mensaje       string                 `protobuf:"bytes,4,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Resultado     string                 `protobuf:"bytes,5,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveedorNotificacionResponse) Reset() {
	*x = ProveedorNotificacionResponse{}
	mi := &file_notificacion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveedorNotificacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveedorNotificacionResponse) ProtoMessage() {}

func (x *ProveedorNotificacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificacion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveedorNotificacionResponse.ProtoReflect.Descriptor instead.
func (*ProveedorNotificacionResponse) Descriptor() ([]byte, []int) {
	return file_notificacion_proto_rawDescGZIP(), []int{2}
}

func (x *ProveedorNotificacionResponse) GetIdProveedor() int32 {
	if x != nil {
		return x.IdProveedor
	}
	return 0
}

func (x *ProveedorNotificacionResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ProveedorNotificacionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProveedorNotificacionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ProveedorNotificacionResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

type ClienteNotificacionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	IdUsuario     int32                   `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	IdCarro       int32                   `protobuf:"varint,2,opt,name=id_carro,json=idCarro,proto3" json:"id_carro,omitempty"`
	Estado        string                  `protobuf:"bytes,3,opt,name=estado,proto3" json:"estado,omitempty"`
	Tipo          string                  `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Productos     []*ProductoNotificacion `protobuf:"bytes,6,rep,name=productos,proto3" json:"productos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClienteNotificacionRequest) Reset() {
	*x = ClienteNotificacionRequest{}
	mi := &file_notificacion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClienteNotificacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteNotificacionRequest) ProtoMessage() {}

func (x *ClienteNotificacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificacion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteNotificacionRequest.ProtoReflect.Descriptor instead.
func (*ClienteNotificacionRequest) Descriptor() ([]byte, []int) {
	return file_notificacion_proto_rawDescGZIP(), []int{3}
}

func (x *ClienteNotificacionRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *ClienteNotificacionRequest) GetIdCarro() int32 {
	if x != nil {
		return x.IdCarro
	}
	return 0
}

func (x *ClienteNotificacionRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ClienteNotificacionRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ClienteNotificacionRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ClienteNotificacionRequest) GetProductos() []*ProductoNotificacion {
	if x != nil {
		return x.Productos
	}
	return nil
}

type ClienteNotificacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	IdCarro       int32                  `protobuf:"varint,2,opt,name=id_carro,json=idCarro,proto3" json:"id_carro,omitempty"`
	Estado        string                 `protobuf:"bytes,3,opt,name=estado,proto3" json:"estado,omitempty"`
	Tipo          string                 `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Resultado     string                 `protobuf:"bytes,6,opt,name=resultado,proto3" json:"resultado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClienteNotificacionResponse) Reset() {
	*x = ClienteNotificacionResponse{}
	mi := &file_notificacion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClienteNotificacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteNotificacionResponse) ProtoMessage() {}

func (x *ClienteNotificacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificacion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteNotificacionResponse.ProtoReflect.Descriptor instead.
func (*ClienteNotificacionResponse) Descriptor() ([]byte, []int) {
	return file_notificacion_proto_rawDescGZIP(), []int{4}
}

func (x *ClienteNotificacionResponse) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *ClienteNotificacionResponse) GetIdCarro() int32 {
	if x != nil {
		return x.IdCarro
	}
	return 0
}

func (x *ClienteNotificacionResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ClienteNotificacionResponse) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ClienteNotificacionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ClienteNotificacionResponse) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

var File_notificacion_proto protoreflect.FileDescriptor

const file_notificacion_proto_rawDesc = "" +
	"\n" +
	"\x12notificacion.proto\x12\fnotificacion\"7\n" +
	"\x14ProductoNotificacion\x12\x1f\n" +
	"\vid_producto\x18\x01 \x01(\x05R\n" +
	"idProducto\"\xd4\x01\n" +
	"\x1cProveedorNotificacionRequest\x12!\n" +
	"\fid_proveedor\x18\x01 \x01(\x05R\vidProveedor\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x18\n" +
	"\amensaje\x18\x04 \x01(\tR\amensaje\x12@\n" +
	"\tproductos\x18\x05 \x03(\v2\".notificacion.ProductoNotificacionR\tproductos\"\xb1\x01\n" +
	"\x1dProveedorNotificacionResponse\x12!\n" +
	"\fid_proveedor\x18\x01 \x01(\x05R\vidProveedor\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x18\n" +
	"\amensaje\x18\x04 \x01(\tR\amensaje\x12\x1c\n" +
	"\tresultado\x18\x05 \x01(\tR\tresultado\"\xe3\x01\n" +
	"\x1aClienteNotificacionRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_carro\x18\x02 \x01(\x05R\aidCarro\x12\x16\n" +
	"\x06estado\x18\x03 \x01(\tR\x06estado\x12\x12\n" +
	"\x04tipo\x18\x04 \x01(\tR\x04tipo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12@\n" +
	"\tproductos\x18\x06 \x03(\v2\".notificacion.ProductoNotificacionR\tproductos\"\xc0\x01\n" +
	"\x1bClienteNotificacionResponse\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_carro\x18\x02 \x01(\x05R\aidCarro\x12\x16\n" +
	"\x06estado\x18\x03 \x01(\tR\x06estado\x12\x12\n" +
	"\x04tipo\x18\x04 \x01(\tR\x04tipo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tresultado\x18\x06 \x01(\tR\tresultado2\xf0\x01\n" +
	"\fNotificacion\x12r\n" +
	"\x15ProveedorNotificacion\x12*.notificacion.ProveedorNotificacionRequest\x1a+.notificacion.ProveedorNotificacionResponse\"\x00\x12l\n" +
	"\x13ClienteNotificacion\x12(.notificacion.ClienteNotificacionRequest\x1a).notificacion.ClienteNotificacionResponse\"\x00B\x1cZ\x1acatalog/internal/grpc;grpcb\x06proto3"

var (
	file_notificacion_proto_rawDescOnce sync.Once
	file_notificacion_proto_rawDescData []byte
)

func file_notificacion_proto_rawDescGZIP() []byte {
	file_notificacion_proto_rawDescOnce.Do(func() {
		file_notificacion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificacion_proto_rawDesc), len(file_notificacion_proto_rawDesc)))
	})
	return file_notificacion_proto_rawDescData
}

var file_notificacion_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_notificacion_proto_goTypes = []any{
	(*ProductoNotificacion)(nil),          // 0: notificacion.ProductoNotificacion
	(*ProveedorNotificacionRequest)(nil),  // 1: notificacion.ProveedorNotificacionRequest
	(*ProveedorNotificacionResponse)(nil), // 2: notificacion.ProveedorNotificacionResponse
	(*ClienteNotificacionRequest)(nil),    // 3: notificacion.ClienteNotificacionRequest
	(*ClienteNotificacionResponse)(nil),   // 4: notificacion.ClienteNotificacionResponse
}
var file_notificacion_proto_depIdxs = []int32{
	0, // 0: notificacion.ProveedorNotificacionRequest.productos:type_name -> notificacion.ProductoNotificacion
	0, // 1: notificacion.ClienteNotificacionRequest.productos:type_name -> notificacion.ProductoNotificacion
	1, // 2: notificacion.Notificacion.ProveedorNotificacion:input_type -> notificacion.ProveedorNotificacionRequest
	3, // 3: notificacion.Notificacion.ClienteNotificacion:input_type -> notificacion.ClienteNotificacionRequest
	2, // 4: notificacion.Notificacion.ProveedorNotificacion:output_type -> notificacion.ProveedorNotificacionResponse
	4, // 5: notificacion.Notificacion.ClienteNotificacion:output_type -> notificacion.ClienteNotificacionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notificacion_proto_init() }
func file_notificacion_proto_init() {
	if File_notificacion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificacion_proto_rawDesc), len(file_notificacion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificacion_proto_goTypes,
		DependencyIndexes: file_notificacion_proto_depIdxs,
		MessageInfos:      file_notificacion_proto_msgTypes,
	}.Build()
	File_notificacion_proto = out.File
	file_notificacion_proto_goTypes = nil
	file_notificacion_proto_depIdxs = nil
}
