apiVersion: v1
kind: Service
metadata:
  name: fx-service
  labels:
    app: fx-service
spec:
  selector:
    app: fx-service
  ports:
    - name: grpc
      port: 50054
      targetPort: 50054
      protocol: TCP
  type: ClusterIP