apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
type: Opaque
stringData:
  DB_SERVER: "mssql,1433"
  DB_NAME: "paymentsDB"
  DB_USER: "sa"
  DB_PASSWORD: "YourStrong@Passw0rd123!"
  JWT_SECRET: "super-secret-jwt-key"