# Etapa 1: Build
FROM node:lts-alpine AS builder

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias (incluye dev para poder compilar)
RUN npm install

# Copiar resto del código fuente
COPY . .

# Compilar la app NestJS (genera dist/)
RUN npm run build

# Etapa 2: Producción
FROM node:lts-alpine AS production

WORKDIR /usr/src/app

# Copiar solo node_modules y dist desde la etapa de build
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY proto ./proto

# Variable de entorno
ENV NODE_ENV=production

# Exponer puerto gRPC
EXPOSE 50051

# Comando de inicio (usa dist/main.js)
CMD ["node", "dist/main.js"]
