// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: payments.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_PENDING   PaymentStatus = 0
	PaymentStatus_PAYMENT_COMPLETED PaymentStatus = 1
	PaymentStatus_PAYMENT_FAILED    PaymentStatus = 2
	PaymentStatus_PAYMENT_CANCELLED PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_PENDING",
		1: "PAYMENT_COMPLETED",
		2: "PAYMENT_FAILED",
		3: "PAYMENT_CANCELLED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_PENDING":   0,
		"PAYMENT_COMPLETED": 1,
		"PAYMENT_FAILED":    2,
		"PAYMENT_CANCELLED": 3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payments_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payments_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{0}
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     int64                  `protobuf:"varint,1,opt,name=usuarioId,proto3" json:"usuarioId,omitempty"`
	OrdenId       string                 `protobuf:"bytes,2,opt,name=ordenId,proto3" json:"ordenId,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	MontoWallet   float64                `protobuf:"fixed64,4,opt,name=montoWallet,proto3" json:"montoWallet,omitempty"`
	MontoTarjeta  float64                `protobuf:"fixed64,5,opt,name=montoTarjeta,proto3" json:"montoTarjeta,omitempty"`
	MetodoPago    string                 `protobuf:"bytes,6,opt,name=metodoPago,proto3" json:"metodoPago,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetUsuarioId() int64 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

func (x *PaymentRequest) GetOrdenId() string {
	if x != nil {
		return x.OrdenId
	}
	return ""
}

func (x *PaymentRequest) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaymentRequest) GetMontoWallet() float64 {
	if x != nil {
		return x.MontoWallet
	}
	return 0
}

func (x *PaymentRequest) GetMontoTarjeta() float64 {
	if x != nil {
		return x.MontoTarjeta
	}
	return 0
}

func (x *PaymentRequest) GetMetodoPago() string {
	if x != nil {
		return x.MetodoPago
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransaccionId string                 `protobuf:"bytes,1,opt,name=transaccionId,proto3" json:"transaccionId,omitempty"`
	Exito         bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=payments.PaymentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetTransaccionId() string {
	if x != nil {
		return x.TransaccionId
	}
	return ""
}

func (x *PaymentResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *PaymentResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *PaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_PENDING
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     int64                  `protobuf:"varint,1,opt,name=usuarioId,proto3" json:"usuarioId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUsuarioId() int64 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	UsuarioId     int64                  `protobuf:"varint,2,opt,name=usuarioId,proto3" json:"usuarioId,omitempty"`
	Monto         float64                `protobuf:"fixed64,3,opt,name=monto,proto3" json:"monto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceRequest) Reset() {
	*x = AddBalanceRequest{}
	mi := &file_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceRequest) ProtoMessage() {}

func (x *AddBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceRequest.ProtoReflect.Descriptor instead.
func (*AddBalanceRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{4}
}

func (x *AddBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *AddBalanceRequest) GetUsuarioId() int64 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

func (x *AddBalanceRequest) GetMonto() float64 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type AddBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NuevoBalance  float64                `protobuf:"fixed64,1,opt,name=nuevoBalance,proto3" json:"nuevoBalance,omitempty"`
	Exito         bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBalanceResponse) Reset() {
	*x = AddBalanceResponse{}
	mi := &file_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBalanceResponse) ProtoMessage() {}

func (x *AddBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBalanceResponse.ProtoReflect.Descriptor instead.
func (*AddBalanceResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{5}
}

func (x *AddBalanceResponse) GetNuevoBalance() float64 {
	if x != nil {
		return x.NuevoBalance
	}
	return 0
}

func (x *AddBalanceResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *AddBalanceResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransaccionId string                 `protobuf:"bytes,1,opt,name=transaccionId,proto3" json:"transaccionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionRequest) GetTransaccionId() string {
	if x != nil {
		return x.TransaccionId
	}
	return ""
}

type TransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransaccionId   string                 `protobuf:"bytes,1,opt,name=transaccionId,proto3" json:"transaccionId,omitempty"`
	UsuarioId       int64                  `protobuf:"varint,2,opt,name=usuarioId,proto3" json:"usuarioId,omitempty"`
	OrdenId         string                 `protobuf:"bytes,3,opt,name=ordenId,proto3" json:"ordenId,omitempty"`
	Total           float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	MetodoPago      string                 `protobuf:"bytes,5,opt,name=metodoPago,proto3" json:"metodoPago,omitempty"`
	FechaCompletado *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=fechaCompletado,proto3" json:"fechaCompletado,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_payments_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionResponse) GetTransaccionId() string {
	if x != nil {
		return x.TransaccionId
	}
	return ""
}

func (x *TransactionResponse) GetUsuarioId() int64 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

func (x *TransactionResponse) GetOrdenId() string {
	if x != nil {
		return x.OrdenId
	}
	return ""
}

func (x *TransactionResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TransactionResponse) GetMetodoPago() string {
	if x != nil {
		return x.MetodoPago
	}
	return ""
}

func (x *TransactionResponse) GetFechaCompletado() *timestamppb.Timestamp {
	if x != nil {
		return x.FechaCompletado
	}
	return nil
}

var File_payments_proto protoreflect.FileDescriptor

const file_payments_proto_rawDesc = "" +
	"\n" +
	"\x0epayments.proto\x12\bpayments\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x01\n" +
	"\x0ePaymentRequest\x12\x1c\n" +
	"\tusuarioId\x18\x01 \x01(\x03R\tusuarioId\x12\x18\n" +
	"\aordenId\x18\x02 \x01(\tR\aordenId\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\x12 \n" +
	"\vmontoWallet\x18\x04 \x01(\x01R\vmontoWallet\x12\"\n" +
	"\fmontoTarjeta\x18\x05 \x01(\x01R\fmontoTarjeta\x12\x1e\n" +
	"\n" +
	"metodoPago\x18\x06 \x01(\tR\n" +
	"metodoPago\"\x98\x01\n" +
	"\x0fPaymentResponse\x12$\n" +
	"\rtransaccionId\x18\x01 \x01(\tR\rtransaccionId\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.payments.PaymentStatusR\x06status\"1\n" +
	"\x11GetBalanceRequest\x12\x1c\n" +
	"\tusuarioId\x18\x01 \x01(\x03R\tusuarioId\"d\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"c\n" +
	"\x11AddBalanceRequest\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\tR\bwalletId\x12\x1c\n" +
	"\tusuarioId\x18\x02 \x01(\x03R\tusuarioId\x12\x14\n" +
	"\x05monto\x18\x03 \x01(\x01R\x05monto\"h\n" +
	"\x12AddBalanceResponse\x12\"\n" +
	"\fnuevoBalance\x18\x01 \x01(\x01R\fnuevoBalance\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje\":\n" +
	"\x12TransactionRequest\x12$\n" +
	"\rtransaccionId\x18\x01 \x01(\tR\rtransaccionId\"\xef\x01\n" +
	"\x13TransactionResponse\x12$\n" +
	"\rtransaccionId\x18\x01 \x01(\tR\rtransaccionId\x12\x1c\n" +
	"\tusuarioId\x18\x02 \x01(\x03R\tusuarioId\x12\x18\n" +
	"\aordenId\x18\x03 \x01(\tR\aordenId\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\x12\x1e\n" +
	"\n" +
	"metodoPago\x18\x05 \x01(\tR\n" +
	"metodoPago\x12D\n" +
	"\x0ffechaCompletado\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffechaCompletado*f\n" +
	"\rPaymentStatus\x12\x13\n" +
	"\x0fPAYMENT_PENDING\x10\x00\x12\x15\n" +
	"\x11PAYMENT_COMPLETED\x10\x01\x12\x12\n" +
	"\x0ePAYMENT_FAILED\x10\x02\x12\x15\n" +
	"\x11PAYMENT_CANCELLED\x10\x032\xb8\x02\n" +
	"\x0ePaymentService\x12E\n" +
	"\x0eProcessPayment\x12\x18.payments.PaymentRequest\x1a\x19.payments.PaymentResponse\x12G\n" +
	"\n" +
	"GetBalance\x12\x1b.payments.GetBalanceRequest\x1a\x1c.payments.GetBalanceResponse\x12G\n" +
	"\n" +
	"AddBalance\x12\x1b.payments.AddBalanceRequest\x1a\x1c.payments.AddBalanceResponse\x12M\n" +
	"\x0eGetTransaction\x12\x1c.payments.TransactionRequest\x1a\x1d.payments.TransactionResponseB\x14Z\x12payment-service/pbb\x06proto3"

var (
	file_payments_proto_rawDescOnce sync.Once
	file_payments_proto_rawDescData []byte
)

func file_payments_proto_rawDescGZIP() []byte {
	file_payments_proto_rawDescOnce.Do(func() {
		file_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)))
	})
	return file_payments_proto_rawDescData
}

var file_payments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payments_proto_goTypes = []any{
	(PaymentStatus)(0),            // 0: payments.PaymentStatus
	(*PaymentRequest)(nil),        // 1: payments.PaymentRequest
	(*PaymentResponse)(nil),       // 2: payments.PaymentResponse
	(*GetBalanceRequest)(nil),     // 3: payments.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 4: payments.GetBalanceResponse
	(*AddBalanceRequest)(nil),     // 5: payments.AddBalanceRequest
	(*AddBalanceResponse)(nil),    // 6: payments.AddBalanceResponse
	(*TransactionRequest)(nil),    // 7: payments.TransactionRequest
	(*TransactionResponse)(nil),   // 8: payments.TransactionResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_payments_proto_depIdxs = []int32{
	0, // 0: payments.PaymentResponse.status:type_name -> payments.PaymentStatus
	9, // 1: payments.TransactionResponse.fechaCompletado:type_name -> google.protobuf.Timestamp
	1, // 2: payments.PaymentService.ProcessPayment:input_type -> payments.PaymentRequest
	3, // 3: payments.PaymentService.GetBalance:input_type -> payments.GetBalanceRequest
	5, // 4: payments.PaymentService.AddBalance:input_type -> payments.AddBalanceRequest
	7, // 5: payments.PaymentService.GetTransaction:input_type -> payments.TransactionRequest
	2, // 6: payments.PaymentService.ProcessPayment:output_type -> payments.PaymentResponse
	4, // 7: payments.PaymentService.GetBalance:output_type -> payments.GetBalanceResponse
	6, // 8: payments.PaymentService.AddBalance:output_type -> payments.AddBalanceResponse
	8, // 9: payments.PaymentService.GetTransaction:output_type -> payments.TransactionResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payments_proto_init() }
func file_payments_proto_init() {
	if File_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payments_proto_goTypes,
		DependencyIndexes: file_payments_proto_depIdxs,
		EnumInfos:         file_payments_proto_enumTypes,
		MessageInfos:      file_payments_proto_msgTypes,
	}.Build()
	File_payments_proto = out.File
	file_payments_proto_goTypes = nil
	file_payments_proto_depIdxs = nil
}
