# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import carro_pb2 as carro__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in carro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GuardarCarro = channel.unary_unary(
                '/carro.Greet/GuardarCarro',
                request_serializer=carro__pb2.GuardarCarroRequest.SerializeToString,
                response_deserializer=carro__pb2.GuardarCarroResponse.FromString,
                _registered_method=True)
        self.ObtenerCarro = channel.unary_unary(
                '/carro.Greet/ObtenerCarro',
                request_serializer=carro__pb2.ObtenerCarroRequest.SerializeToString,
                response_deserializer=carro__pb2.ObtenerCarroResponse.FromString,
                _registered_method=True)
        self.ActualizarEstado = channel.unary_unary(
                '/carro.Greet/ActualizarEstado',
                request_serializer=carro__pb2.ActualizarEstadoRequest.SerializeToString,
                response_deserializer=carro__pb2.ActualizarEstadoResponse.FromString,
                _registered_method=True)
        self.ActualizarFecha = channel.unary_unary(
                '/carro.Greet/ActualizarFecha',
                request_serializer=carro__pb2.ActualizarFechaRequest.SerializeToString,
                response_deserializer=carro__pb2.ActualizarFechaResponse.FromString,
                _registered_method=True)


class GreetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GuardarCarro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCarro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarEstado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarFecha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GuardarCarro': grpc.unary_unary_rpc_method_handler(
                    servicer.GuardarCarro,
                    request_deserializer=carro__pb2.GuardarCarroRequest.FromString,
                    response_serializer=carro__pb2.GuardarCarroResponse.SerializeToString,
            ),
            'ObtenerCarro': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCarro,
                    request_deserializer=carro__pb2.ObtenerCarroRequest.FromString,
                    response_serializer=carro__pb2.ObtenerCarroResponse.SerializeToString,
            ),
            'ActualizarEstado': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarEstado,
                    request_deserializer=carro__pb2.ActualizarEstadoRequest.FromString,
                    response_serializer=carro__pb2.ActualizarEstadoResponse.SerializeToString,
            ),
            'ActualizarFecha': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarFecha,
                    request_deserializer=carro__pb2.ActualizarFechaRequest.FromString,
                    response_serializer=carro__pb2.ActualizarFechaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carro.Greet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carro.Greet', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GuardarCarro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carro.Greet/GuardarCarro',
            carro__pb2.GuardarCarroRequest.SerializeToString,
            carro__pb2.GuardarCarroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCarro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carro.Greet/ObtenerCarro',
            carro__pb2.ObtenerCarroRequest.SerializeToString,
            carro__pb2.ObtenerCarroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarEstado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carro.Greet/ActualizarEstado',
            carro__pb2.ActualizarEstadoRequest.SerializeToString,
            carro__pb2.ActualizarEstadoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarFecha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carro.Greet/ActualizarFecha',
            carro__pb2.ActualizarFechaRequest.SerializeToString,
            carro__pb2.ActualizarFechaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
